export enum LifecycleState {
  DRAFT = "DRAFT",
  PUBLISHED = "PUBLISHED",
  PUBLISH_REQUESTED = "PUBLISH_REQUESTED",
  PUBLISH_FAILED = "PUBLISH_FAILED ",
}

export enum Visibility {
  CONNECTIONS = "CONNECTIONS",
  PUBLIC = "PUBLIC",
  LOGGED_IN = "LOGGED_IN",
  CONTAINER = "CONTAINER",
}
